<?php

$categorias_servicios = [
    'Psicologo' => [
        'Psicología Clínica' => [
            'Terapia Individual (Adultos)',
            'Terapia de Pareja',
            'Terapia Familiar',
            'Terapia Cognitivo-Conductual (TCC)',
            'Terapia Psicoanalítica',
        ],
        'Salud Mental Específica' => [
            'Manejo de Ansiedad y Estrés',
            'Tratamiento de Depresión',
            'Trastornos de la Alimentación',
            'Fobias y Pánico',
            'Duelo y Pérdida',
        ],
        'Neuropsicología' => [
            'Evaluación Neuropsicológica',
            'Rehabilitación Cognitiva',
            'Trastornos del Desarrollo',
        ],
        'Psicología Infantil y Juvenil' => [
            'Problemas de Conducta Infantil',
            'Orientación a Padres',
            'Terapia para Adolescentes',
            'TDAH y Dificultades de Aprendizaje',
        ],
        'Otros Servicios Psicológicos' => [
            'Sesiones Online (Telepsicología)',
            'Evaluación y Diagnóstico Clínico',
            'Supervisión Clínica para Colegas',
            'Orientación Vocacional',
        ]
    ],
    
    'Proveedor' => [
        'Servicios empresariales y profesionales' => [
            'Consultoría empresarial',
            'Asesoría legal',
            'Contabilidad y finanzas',
            'Recursos humanos y reclutamiento',
            'Traducción e interpretación',
            'Auditoría',
            'Coaching ejecutivo',
            'Gestión de proyectos',
            'Servicios administrativos',
            'Marketing y publicidad',
            'Relaciones públicas',
            'Investigación de mercado',
            'Formación y capacitación empresarial',
        ],
        'Servicios tecnológicos y digitales' => [
            'Desarrollo de software',
            'Diseño web y UX/UI',
            'Mantenimiento informático',
            'Ciberseguridad',
            'Soporte técnico',
            'Servicios en la nube',
            'Análisis de datos / Big Data',
            'Inteligencia artificial y automatización',
            'SEO / SEM',
            'Gestión de redes sociales',
            'Producción audiovisual / multimedia',
            'Diseño gráfico',
            'Hosting y dominios',
        ],
        'Servicios técnicos e industriales' => [
            'Mantenimiento industrial',
            'Electricidad y electrónica',
            'Fontanería',
            'Carpintería',
            'Mecánica y reparación de vehículos',
            'Ingeniería y arquitectura',
            'Topografía y geotecnia',
            'Construcción y reformas',
            'Control de calidad',
            'Energías renovables',
            'Instalaciones de climatización',
        ],
        'Servicios para el hogar' => [
            'Limpieza y desinfección',
            'Jardinería y paisajismo',
            'Pintura y decoración',
            'Mudanzas',
            'Seguridad (alarmas, cámaras, vigilancia)',
            'Mantenimiento del hogar',
            'Cuidado de mascotas',
            'Cuidado de personas mayores o niños',
            'Domótica y automatización del hogar',
        ],
        'Servicios de salud y bienestar' => [
            'Medicina general y especializada',
            'Fisioterapia',
            'Nutrición',
            'Estética y belleza',
            'Masajes y spa',
            'Entrenamiento personal',
            'Servicios farmacéuticos y de laboratorio',
        ],
        'Servicios educativos' => [
            'Clases particulares',
            'Cursos online',
            'Tutorías escolares',
            'Formación profesional',
            'Academias de idiomas',
            'Preparación de exámenes',
            'Educación infantil',
            'Educación especial',
            'Consultoría educativa',
            'Coaching académico',
        ],
        'Servicios logísticos y de transporte' => [
            'Transporte de mercancías',
            'Courier y mensajería',
            'Logística y distribución',
            'Almacenamiento',
            'Transporte público y privado',
            'Servicios portuarios y aeroportuarios',
            'Transporte de personas (taxis, VTC, autobuses)',
            'Mudanzas internacionales',
        ],
        'Servicios de hostelería y alimentación' => [
            'Restaurantes y bares',
            'Catering',
            'Organización de eventos',
            'Repostería / panadería artesanal',
            'Comida a domicilio',
            'Food trucks',
            'Gestión hotelera',
            'Turismo gastronómico',
        ],
        'Servicios culturales y de entretenimiento' => [
            'Producción de eventos',
            'Organización de conciertos y festivales',
            'Fotografía y video',
            'Alquiler de equipos audiovisuales',
            'Animación infantil',
            'Agencias de talentos',
            'Espectáculos y teatro',
            'Turismo y guías turísticos',
        ],
        'Servicios ambientales y sociales' => [
            'Consultoría ambiental',
            'Reciclaje y gestión de residuos',
            'Conservación del medio ambiente',
            'Responsabilidad social corporativa (RSC)',
            'ONGs y fundaciones',
            'Voluntariado',
            'Educación ambiental',
        ],
        'Servicios financieros' => [
            'Banca y créditos',
            'Seguros',
            'Inversiones',
            'Asesoría fiscal',
            'Fintech',
            'Criptomonedas y blockchain',
            'Microfinanzas',
        ],
        'Servicios de viajes y turismo' => [
            'Agencias de viajes',
            'Reservas de vuelos y hoteles',
            'Guías turísticos',
            'Alquiler de vehículos',
            'Turismo de aventura',
            'Turismo sostenible',
            'Viajes corporativos',
        ],
        'Otros' => [
            'Otro',
        ]
    ]
];